[project]
name = "marmalade"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "CL Dixon", email = "cl_dixon@icloud.com" }
]
requires-python = ">=3.12"
dependencies = [
    "transformers>=4.57.1",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
